resources:
- name: nist-800-53
  type: git
  source:
    uri: git@github.com:opencontrol/certifications.git
    branch: master
    private_key: {{github-private-key}}

- name: cloudfoundry-controls
  type: git
  source:
    uri: git@github.com:opencontrol/components.git
    branch: master
    private_key: {{github-private-key}}

- name: example-fedramp-system
  type: git
  source:
    uri: git@github.com:opencontrol/example-pipelines.git
    branch: master
    private_key: {{github-private-key}}
# TODO: Put a Semver in here somewhere

- name: gitbook-task
  type: git
  source:
    uri: git@github.com:opencontrol/concourse-gitbook-task.git
    branch: master
    private_key: {{github-private-key}}

- name: nessus-task
  type: git
  source:
    uri: git@github.com:opencontrol/concourse-nessus-task.git
    branch: master
    private_key: {{github-private-key}}

- name: yaml-to-markdown-task
  type: git
  source:
    uri: git@github.com:opencontrol/yaml-to-markdown-task.git
    branch: master
    private_key: {{github-private-key}}

jobs:
- name: 800-53-unit
  plan:
  - { get: certifications, resource: nist-800-53, trigger: true }
  - task: unit
    file: certifications/task-unit-test.yml

- name: cf-control-unit
  plan:
  - { get: components, resource: cloudfoundry-controls, trigger: true }
  - task: unit
    file: components/task-unit-test.yml

- name: merge-yamls
  plan:
  - aggregate:
    - get: cloudfoundry-controls
      passed: [cf-control-unit]
      trigger: true
    - get: nist-800-53
      passed: [800-53-unit]
      trigger: true
    - get: example-fedramp-system
      trigger: true

  - task: jinja-merge
    config:
      platform: linux
      image: docker:///opencontrol/jinja
      inputs:
      - name: example-fedramp-system
        path: .
      - name: nist-800-53
        path: nist-800-53
      - name: cloudfoundry-controls
        path: cloudfoundry-controls
      run:
        path: ./jinjame.py
        args:
          - nist-800-53/data/certifications/*.y*ml
          - nist-800-53/data/standards/*.y*ml
          - cloudfoundry-controls/data/components/**/*.y*ml
          - output/generated-system.yml

  - task: git-add
    config:
      platform: linux
      image: docker:///opencontrol/spruce
      inputs:
      - name: jinja-merge
      run:
        path: git-add-all
        args: [jinja-merge/output]

  - put: example-fedramp-system
    params:
      repository: git-add/jinja-merge/output

- name: yaml-to-markdown
  plan:
  - get: example-fedramp-system
    passed: [merge-yamls]
    trigger: true

  - task: jinja-merge
    config:
      platform: linux
      image: docker:///opencontrol/jinja
      inputs:
      - name: example-fedramp-system
        path: .
      run:
        path: ./jinjame.py
        args:
          - --template_path='templates/ssp-gitbook'
          - --template_file='gitbook-markdown.template'
          - output/generated-system.yml
          - output/generated-system.md

- name: gitbook-output-pdf
  plan:
  - get: example-fedramp-system
    passed: [merge-yamls]
    trigger: true
  - get: gitbook-task
    trigger: true
  - task: gitbook-pdf
    file: gitbook-task/task.yml
    config:
      params:
        book-repo: example-fedramp-system
#  - put: pws-system-details

- name: gitbook-output-poams
  plan:
  - get: example-fedramp-system
    passed: [merge-yamls]
    trigger: true
  - get: gitbook-task
    trigger: true
  - task: gitbook-pdf
    file: gitbook-task/waiver.yml
    config:
      params:
        book-repo: example-fedramp-system
  #- put: pws-system-details

- name: output-nessus-config
  plan:
  - get: example-fedramp-system
    passed: [merge-yamls]
    trigger: true
  - get: nessus-task
    trigger: true
  - task: nessus-config-generation
    file: nessus-task/waiver.yml
    config:
      params:
        book-repo: example-fedramp-system
#  - put: pws-system-details
